### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#1]
## Description

Set up the dev environment.

## Acceptance criteria
- [x] Everything is ready for development of the first story.

## Tasks
- [x] create react app
- [x] set up storybook
- [x] create .prettierrc
- [x] set up deployment to Vercel
- [x] set up cypress

## Size
medium
