### ISSUE TITLE
Result/details

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#10]
## Value statement - a requirement, not a solution
As a test-taker
I need to see details about my personality type
so that I can better cope with it. 

## Description
![Ergebnis_2](https://user-images.githubusercontent.com/10497968/91414004-36a28300-e84c-11ea-888c-f06643cd9df4.png)

## Acceptance criteria
- [x] Show the relevant content according to the test result
- [x] phone numbers should be tappable

## Tasks
- [x] add link to Result/intro
- [x] write component test
- [x] save (placeholder) content in data file
- [x] create component
- [x] add component to app

## Size
 small
