### ISSUE TITLE
Create Design

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#12]
##Tasks

- [x] Choose colors
- [x] Choose fonts
- [x]  Find illustrations and/or images
- [x]  Design the questionnaire page
- [x] Design the homepage
