### ISSUE TITLE
Implement basic design elements

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#17]
## Description (Text, Scribble, Wireframe, Design)

Add basic design elements according to the design on adobe xd:
https://xd.adobe.com/view/26d6498e-323d-4a1b-9b55-5b7b7560928c-7385/

## Acceptance criteria
- [x] buttons
- [x] fonts and typo hierarchy
- [x] colors as CSS-variables
- [x] headline underline
- [x] custom bullet points: checkmark icon

## Tasks
- [x] component test for each component
- [x]  storybook for each component
- [x] add components to app

## Size
medium
