### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#2]
## Value statement 
As a visitor
I need to read a description of the app
so that I can decide if I want ot continue.

## Description (Text, Scribble, Wireframe, Design)
![Home](https://user-images.githubusercontent.com/10497968/91413666-c0058580-e84b-11ea-8dad-334da61aec50.png)
The button should be visible, but not have any functionality yet.

## Acceptance criteria
- [x] A description of the app is visible

## Tasks
- [x] Write component test 
- [x] Create  Homepage component
- [x] Create Button component
- [x] Add Homepage to Storybook
- [x] Add Homepage to App

## Size
small

**Comment by karstenlenz** [comment]
Logo has been replaced it with an illustration. Might change later, if the App gets a real name.

**Comment by manuelpapa** [comment]
Good job on the structure of your user stories. Everything is well-prepared to understand, so that a team member could easily join and take over a story. Keep going!
Great topic btw., looking forward to seeing the finished result!
