### ISSUE TITLE
feat/improved motive selection

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#25]
## Value statement 
As a test-taker
I need to have an engaging experience choosing motives
so that I feel motivated to complete the test.

## Description (Text, Scribble, Wireframe, Design)

Start
![Motives_new_start](https://user-images.githubusercontent.com/10497968/92476184-d5c96200-f1de-11ea-8040-ad7f16b4be68.png)

Confirmation
![Motives_new_confirm](https://user-images.githubusercontent.com/10497968/92476217-e2e65100-f1de-11ea-9d1d-7c41171ac7e5.png)

The text above the button "Klicken Sie..." has been removed.

## Acceptance criteria
- [x] at the start the "weiter" button is disabled
- [x] clicking on a motive on the list moves it to the first free slot
- [x] clicking on a motive in the list removes it
- [x] motives can be dragged around and put on a slot
- [x] if a slot is already filled, the current motive will replace the previous motive. The previous motive will return to the list.
- [x] after all 3 slots have been filled, the "weiter" button becomes active and the confirmation text appears
- [x] clicking on the "i" button open the layer with information about the motives like before

## Tasks
- [x] write test
- [x] create new selection component
- [x] integrate component into storybook
- [x] integrate component into app

## Size
large
