### ISSUE TITLE
feat/improved questionnaire

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#26]
## Value statement 
As a test-taker
I need to have an engaging experience answering the questionnaire
so that I feel motivated to complete the test.

## Description (Text, Scribble, Wireframe, Design)

![Questionnaire_swipe](https://user-images.githubusercontent.com/10497968/92479833-59d21880-f1e4-11ea-94bd-8fb597dbcc1b.png)
![Questionnaire_swipe_2](https://user-images.githubusercontent.com/10497968/92480285-fc8a9700-f1e4-11ea-8f8d-1f5be5cb5b58.png)

There will be no animation in this version. Animated cards may be added in a later user story.

## Acceptance criteria
- [x] "yes" and "no" can be selected by clicking the corresponding button
- [x] "yes" or "no" can also be selected by swipping left(left) or right(yes)
- [x] while swiping the card and button get a colored outline: primary for left, secondary for right
- [x] the outline gets stronger the further the card is dragged to the side
- [x] while swiping the other button is disabled
- [x] if you let go while swiping and the card is not near the screen corder the card gets returned to the center position
- [x] if the card is near the screen border this will select an answer. The exact area needs to be decided in testing.

## Tasks
- [x] write test
- [x] create new selection component
- [x] integrate component into storybook
- [x] integrate component into app

## Size
large
