### ISSUE TITLE
Motives/intro

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#3]
## Value statement - a requirement, not a solution
As a test-taker
I need to understand what motives are
so that I can sort the motives. 

## Description
![Motive_1](https://user-images.githubusercontent.com/10497968/91413738-d7447300-e84b-11ea-83c5-55739603974a.png)
A placeholder image can be used instead of the mood image.

## Acceptance criteria
- [x] Motives have been described.

## Tasks
- [x] Link the Button on Homepage to this page using React Router
- [x] Write test
- [x] Create component MotivesIntro
- [x] Add MotivesIntro to Storybook
- [x] Add MotivesIntro to App

## Size
small
