### ISSUE TITLE
feat/additional-questionnaires

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#31]
## Value statement
As a test-taker
I need to be able to take additional tests
so that I can discover more about my personality.

## Description 
There are 9 different personality styles with one questionnaire each. In order to give the test-takers a quick result, the app currently only offers the 2 most-likely personality styles based on the motive choice. Testing has shown that this is problematic because:
- some users score low on the first two tests and feel disappointed  because they did not get a "positive" result
- some users have more than 2 dominant personality styles and would like to do all the tests

To solve this, users should optionally take additional tests after the first round. After each additional questionnaire they should visit a more compact result screen with the ranked personality styles(see design).

![Result_new](https://user-images.githubusercontent.com/10497968/93323394-daac9800-f814-11ea-98b6-d4d7cb8dbf1a.png)

## Acceptance criteria
- [x] on the existing result screen the user can start another test
- [x] after completing the additional questionnaire the user will come to a compact result screen listing all the tests
- [x] the test results are sorted by numbers of positive answers
- [x] the bar showing the matching percentage should display with an animation after loading the page
- [x] on the personality style info page the user can click on a back button to return to the previous page

## Tasks
- [x] add back button to personality style info page
- [x] add info text to result page
- [x] add button to start another questionnaire on result page
- [x] modify questionnaire component so that it can do one more test
- [x] modify result page to receive more than 2 test results
- [x] build the component FurtherResults
- [x] update personalityStyleData to include the adjectiv for each style
- [x] write tests
- [x] add component to Storybook
- [x] implement component in App

## Size
medium
