### ISSUE TITLE
feat/header navigation

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#35]
## Value statement - a requirement, not a solution
As a user
I need navigate back to the homepage
so that I can visit a different section.

## Description (Text, Scribble, Wireframe, Design)

<img width="339" alt="image" src="https://user-images.githubusercontent.com/10497968/93932666-d3a7ed00-fd20-11ea-8a58-e321f023392e.png">

The logo will first be added as a placeholder image until #34 is completed.
## Acceptance criteria
- [x] The user can go back one step in history.
- [x] The user can go back to the homepage from every page.
- [x] the navigation is shown on every page except for the homepage

## Tasks
- [x] write test
- [x] add to storybook
- [x] add to App.

## Size
small
