### ISSUE TITLE
feat/journal

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#36]
## Value statement - a requirement, not a solution
As a user
I need to write journal entries
so that I can keep track of my behavior over time.

## Description

![Journal_List](https://user-images.githubusercontent.com/10497968/93721379-17b7b800-fb90-11ea-8481-dcd22b241fe5.png)
![Journal_List_2](https://user-images.githubusercontent.com/10497968/93721376-15edf480-fb90-11ea-9418-42ec2290753b.png)
![Journal_Entry](https://user-images.githubusercontent.com/10497968/93721375-15555e00-fb90-11ea-8358-e36ea097f657.png)

## Acceptance criteria
- [x] The user can navigate to the journal page from the homepage and results page
- [x] All previous entries can be seen on the list page.
- [x] If there is no entry, there is a message that asks user to enter a new note
- [x] New journal entries can be added
- [x] Previous entries can be deleted

## Tasks
- [x] write tests
- [x] create journal list component
- [x] create journal form component
- [x]  read from and save to local storage
- [x] add components to storybook
- [x] add components to app

## Size
large

**Comment by annidrumm** [comment]
Your App looks really good Karsten! I like your design.

QA:
- navigation works 
-  it is possible to add long and short journal entries
-  deleting a journal works fine as well

You could think about max. or min. word entries but apart from that it looks great. 👍
