### ISSUE TITLE
feat/updated-homepage

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#37]
## Value statement - a requirement, not a solution
As a visitor
I need to understand what the app offers
so that I can decide if I want to use it.

## Description (Text, Scribble, Wireframe, Design)
With the addition of the journal function (#36) the homepage needs to offer access to both questionnaire and journal sections. Both parts need to be introduced and have some sort of link component.

![Home_New](https://user-images.githubusercontent.com/10497968/94057846-7b382480-fde0-11ea-921d-e7dc1cd09fb3.png)

## Acceptance criteria
- [x] the user can start the motive selection
- [x] the user can got to the journal page

## Tasks
- [x] update Homepage component
- [x] write/update tests
- [x] update Storybook (if necessary)

## Size
medium
