### ISSUE TITLE
Motives/Selection

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#4]
## Value statement 
As a test-taker
I need to choose and sort my most important motives
so that I can get the correct test for my personality.

## Description
![Motive_2](https://user-images.githubusercontent.com/10497968/91314095-7a4aad80-e7b6-11ea-9651-b8e61b97623a.png)
![Motive_3](https://user-images.githubusercontent.com/10497968/91314098-7b7bda80-e7b6-11ea-9cac-0059409df7a5.png)
The info-icon is not part of this story (see Motives/Overlay). 
Confirmation ist not part of this story. (see  Motives/Confirmation)

## Acceptance criteria
- [x] Clicking on a motive adds it to the list
- [x] After clicking a button it is disabled
- [x] After selecting 3 motives select the closest-matching personality-type and start the corresponding test.

## Tasks
- [x] write test
- [x] Create component MotivesSelection
- [x] Save selected motives in state
- [x] create algorithm to assign questionnaires
- [x] save questionnaires in state
- [x] input questionnaire data for all tests
- [x] Add MotivesSelection to Storybook
- [x] Add MotivesSelection to App

## Size
small

**Comment by karstenlenz** [comment]
Test-URL for PR: https://capstone-project-git-feat-motives.karstenlenz.vercel.app/
