### ISSUE TITLE
Create progressive web app

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#42]
## Description (Text, Scribble, Wireframe, Design)
The app should work as a progressive web app.

## Acceptance criteria
- [x] allow app to be installed on smartphone
- [x] app can be used offline

## Tasks
- [x] register serviceWorker
- [x] implement required icons
- [x] create tests (if possible)

## Size
medium

**Comment by karstenlenz** [comment]
I did some research and it seems, the PWA capabilities can't be properly tested using jest or cypress.
