### ISSUE TITLE
task/misc user-feedback

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#43]
## Description (Text, Scribble, Wireframe, Design)
User-testing revealed a few things to optimize:

- The descriptions on the result screen are still a little bit confusing. Some users aren't sure what the result tells them, especially if they only have low results on the test.
- Buttons are lacking a margin (seems to have been accidentally removed)
- Text tonality is not consistent. Some texts are very serious, others more light-hearted. Users tend to prefer the light-hearted text more.
- some typos

## Acceptance criteria
- [x] text tonality is consistent throughout the app
- [x] buttons have margin
- [x] the test process and the result is easy to understand

## Tasks

- [x] review and update all text content
- [x] review and update result screen
- [x] update tests
- [x] update storybook (if necessary)

## Size
medium
