### ISSUE TITLE
task/ responsive web design

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#45]
## Description (Text, Scribble, Wireframe, Design)
Currently the app has only been optimized for mobile devices. It should be updated, so every device and screen size offers a good UX. the max-width may be limited.

## Acceptance criteria
- [x] the app offers a good UX on every screen size.
- [x] the app can be used with touch or mouse controls.

## Tasks
- [x] update styling for all necessary components
- [x] update tests
- [x] update Storybook (if necessary)

## Size
medium
