### ISSUE TITLE
Motives/Overlay

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#5]
## Value statement - a requirement, not a solution
As a test-taker
I need to read a description of each motive
so that I can choose the most relevant ones.

## Description
![Motive_Overlay](https://user-images.githubusercontent.com/10497968/91413808-f2af7e00-e84b-11ea-8379-2052d4816cb3.png)
At first only dummy textd will be implemented. Final text will be added later.

## Acceptance criteria
- [x] each info-icon opens the corresponding info-layer
- [x] the layer can be closed by clicking the x-icon or clicking outside the layer

## Tasks
- [x] write test
- [x] create component
- [x] add component to storybook
- [x] add component to Motives

## Size
small

**Comment by carolinwagner** [comment]
passed my QA without any striking :-) 
I like that the "i" buttons can be clicked when the corresponding "need" button is already disabled - hope that was on purpose.
