### ISSUE TITLE
Motives/Confirmation

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#6]
## Value statement
As a test-taker
I need to confirm the order of motives
so that I can be sure to get the correct test.

## Description 
![Motive_4](https://user-images.githubusercontent.com/10497968/91316937-b59aab80-e7b9-11ea-9cab-125cc8591e77.png)

## Acceptance criteria
- [ ] confirm button leads to next step (Motives/result)
- [ ] back restarts the selection process

## Tasks
- [ ] write test
- [ ] Create component 
- [ ] Add component to Storybook
- [ ] Add component to App

## Size
small

**Comment by karstenlenz** [comment]
Obsolete since the new UI has been implemented.
