### ISSUE TITLE
Questionnaire/intro

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#7]
## Value statement 
As a test-taker
I need to know what to expect from the test
so that I don't get confused during the test.

## Description
![Fragebogen_1](https://user-images.githubusercontent.com/10497968/91318442-84bb7600-e7bb-11ea-97cb-88ebdd9e17de.png)

## Acceptance criteria
- [x] explain test procedure
- [x] start first questionnaire on button click

## Tasks

- [x] write component test 
- [x] create component
- [x] add component to storybook
- [x] add component to app

## Size
 Small
