### ISSUE TITLE
 Questionnaire/input

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#8]
## Value statement - a requirement, not a solution
As a test-taker 
I need to fill out a questionnaire
so that I can discover if I match a certain personality type.

## Description 
![Fragebogen_2](https://user-images.githubusercontent.com/10497968/91319064-3a86c480-e7bc-11ea-9495-393790c78f8a.png)
At first only implement personality type "narzistische Persönlichkeitsstil" as an example. The other styles will be added after Motive-Selection works.

## Acceptance criteria
- [x] Answers are saved
- [x] the progress is shown (questionnaire X/X, question X/8)
- [x] At the end the user can see how many times they answered yes.
- [x] If the user answered yes more than 5 times, show  that the personality type matches the user.

## Tasks
- [x] write component test
- [x] create component
- [x] save answers in state
- [x] Add basic styles
- [x] add component to storybook
- [x] add component to app

## Size
medium

**Comment by karstenlenz** [comment]
Test-URL: https://capstone-project-e5s1biuky.vercel.app/
