### ISSUE TITLE
Result/intro

### ISSUE THREAD

**Issue by karstenlenz** [karstenlenz/capstone-project#9]
## Value statement 
As a test-taker
I need to see my dominant personality type
so that I can learn something about myself.

## Description
![Ergebnis_1](https://user-images.githubusercontent.com/10497968/91413969-28546700-e84c-11ea-9365-b2bf5e9d0639.png)

Styling is not part of the story. The content of the page has changed slightly (see comment below)

## Acceptance criteria
- [x] Show the most relevant personality type.
- [x] link to psychology help website: https://www.psychenet.de/de/hilfe-finden/schnelle-hilfe/krisenanlaufstellen.html

## Tasks
- [x] add link to final step of questionnaire
- [x] write component test
- [x] write algorithm to evaluate dominant personality type
- [x] create component
- [x] add component to storybook
- [x] add component to app

## Size
medium

**Comment by karstenlenz** [comment]
After talking to my consulting psychotherapist, we decided to always do 2 tests that match best and then show 2 results, too. The wireframe hasn't been updated.

**Comment by karstenlenz** [comment]
After QA I rebuild the whole test logic. I removed most of the states and save the results in the URL. This seems to work better with browser back functions.
